	soc_system u0 (
		.clk_clk                               (<connected-to-clk_clk>),                               //                       clk.clk
		.conv1d_done_export                    (<connected-to-conv1d_done_export>),                    //               conv1d_done.export
		.conv1d_hn_address                     (<connected-to-conv1d_hn_address>),                     //                 conv1d_hn.address
		.conv1d_hn_clken                       (<connected-to-conv1d_hn_clken>),                       //                          .clken
		.conv1d_hn_chipselect                  (<connected-to-conv1d_hn_chipselect>),                  //                          .chipselect
		.conv1d_hn_write                       (<connected-to-conv1d_hn_write>),                       //                          .write
		.conv1d_hn_readdata                    (<connected-to-conv1d_hn_readdata>),                    //                          .readdata
		.conv1d_hn_writedata                   (<connected-to-conv1d_hn_writedata>),                   //                          .writedata
		.conv1d_hn_byteenable                  (<connected-to-conv1d_hn_byteenable>),                  //                          .byteenable
		.conv1d_start_export                   (<connected-to-conv1d_start_export>),                   //              conv1d_start.export
		.conv1d_xn_address                     (<connected-to-conv1d_xn_address>),                     //                 conv1d_xn.address
		.conv1d_xn_clken                       (<connected-to-conv1d_xn_clken>),                       //                          .clken
		.conv1d_xn_chipselect                  (<connected-to-conv1d_xn_chipselect>),                  //                          .chipselect
		.conv1d_xn_write                       (<connected-to-conv1d_xn_write>),                       //                          .write
		.conv1d_xn_readdata                    (<connected-to-conv1d_xn_readdata>),                    //                          .readdata
		.conv1d_xn_writedata                   (<connected-to-conv1d_xn_writedata>),                   //                          .writedata
		.conv1d_xn_byteenable                  (<connected-to-conv1d_xn_byteenable>),                  //                          .byteenable
		.conv1d_yn_address                     (<connected-to-conv1d_yn_address>),                     //                 conv1d_yn.address
		.conv1d_yn_clken                       (<connected-to-conv1d_yn_clken>),                       //                          .clken
		.conv1d_yn_chipselect                  (<connected-to-conv1d_yn_chipselect>),                  //                          .chipselect
		.conv1d_yn_write                       (<connected-to-conv1d_yn_write>),                       //                          .write
		.conv1d_yn_readdata                    (<connected-to-conv1d_yn_readdata>),                    //                          .readdata
		.conv1d_yn_writedata                   (<connected-to-conv1d_yn_writedata>),                   //                          .writedata
		.conv1d_yn_byteenable                  (<connected-to-conv1d_yn_byteenable>),                  //                          .byteenable
		.fft_bfp_exponent_export               (<connected-to-fft_bfp_exponent_export>),               //          fft_bfp_exponent.export
		.fft_inverse_export                    (<connected-to-fft_inverse_export>),                    //               fft_inverse.export
		.fft_wrapper_done_export               (<connected-to-fft_wrapper_done_export>),               //          fft_wrapper_done.export
		.fft_wrapper_start_export              (<connected-to-fft_wrapper_start_export>),              //         fft_wrapper_start.export
		.fft_xn_imag_address                   (<connected-to-fft_xn_imag_address>),                   //               fft_xn_imag.address
		.fft_xn_imag_clken                     (<connected-to-fft_xn_imag_clken>),                     //                          .clken
		.fft_xn_imag_chipselect                (<connected-to-fft_xn_imag_chipselect>),                //                          .chipselect
		.fft_xn_imag_write                     (<connected-to-fft_xn_imag_write>),                     //                          .write
		.fft_xn_imag_readdata                  (<connected-to-fft_xn_imag_readdata>),                  //                          .readdata
		.fft_xn_imag_writedata                 (<connected-to-fft_xn_imag_writedata>),                 //                          .writedata
		.fft_xn_imag_byteenable                (<connected-to-fft_xn_imag_byteenable>),                //                          .byteenable
		.fft_xn_re_address                     (<connected-to-fft_xn_re_address>),                     //                 fft_xn_re.address
		.fft_xn_re_clken                       (<connected-to-fft_xn_re_clken>),                       //                          .clken
		.fft_xn_re_chipselect                  (<connected-to-fft_xn_re_chipselect>),                  //                          .chipselect
		.fft_xn_re_write                       (<connected-to-fft_xn_re_write>),                       //                          .write
		.fft_xn_re_readdata                    (<connected-to-fft_xn_re_readdata>),                    //                          .readdata
		.fft_xn_re_writedata                   (<connected-to-fft_xn_re_writedata>),                   //                          .writedata
		.fft_xn_re_byteenable                  (<connected-to-fft_xn_re_byteenable>),                  //                          .byteenable
		.fft_yn_imag_address                   (<connected-to-fft_yn_imag_address>),                   //               fft_yn_imag.address
		.fft_yn_imag_clken                     (<connected-to-fft_yn_imag_clken>),                     //                          .clken
		.fft_yn_imag_chipselect                (<connected-to-fft_yn_imag_chipselect>),                //                          .chipselect
		.fft_yn_imag_write                     (<connected-to-fft_yn_imag_write>),                     //                          .write
		.fft_yn_imag_readdata                  (<connected-to-fft_yn_imag_readdata>),                  //                          .readdata
		.fft_yn_imag_writedata                 (<connected-to-fft_yn_imag_writedata>),                 //                          .writedata
		.fft_yn_imag_byteenable                (<connected-to-fft_yn_imag_byteenable>),                //                          .byteenable
		.fft_yn_re_address                     (<connected-to-fft_yn_re_address>),                     //                 fft_yn_re.address
		.fft_yn_re_clken                       (<connected-to-fft_yn_re_clken>),                       //                          .clken
		.fft_yn_re_chipselect                  (<connected-to-fft_yn_re_chipselect>),                  //                          .chipselect
		.fft_yn_re_write                       (<connected-to-fft_yn_re_write>),                       //                          .write
		.fft_yn_re_readdata                    (<connected-to-fft_yn_re_readdata>),                    //                          .readdata
		.fft_yn_re_writedata                   (<connected-to-fft_yn_re_writedata>),                   //                          .writedata
		.fft_yn_re_byteenable                  (<connected-to-fft_yn_re_byteenable>),                  //                          .byteenable
		.fir_done_export                       (<connected-to-fir_done_export>),                       //                  fir_done.export
		.fir_error_export                      (<connected-to-fir_error_export>),                      //                 fir_error.export
		.fir_start_export                      (<connected-to-fir_start_export>),                      //                 fir_start.export
		.fir_xn_address                        (<connected-to-fir_xn_address>),                        //                    fir_xn.address
		.fir_xn_clken                          (<connected-to-fir_xn_clken>),                          //                          .clken
		.fir_xn_chipselect                     (<connected-to-fir_xn_chipselect>),                     //                          .chipselect
		.fir_xn_write                          (<connected-to-fir_xn_write>),                          //                          .write
		.fir_xn_readdata                       (<connected-to-fir_xn_readdata>),                       //                          .readdata
		.fir_xn_writedata                      (<connected-to-fir_xn_writedata>),                      //                          .writedata
		.fir_xn_byteenable                     (<connected-to-fir_xn_byteenable>),                     //                          .byteenable
		.fir_yn_address                        (<connected-to-fir_yn_address>),                        //                    fir_yn.address
		.fir_yn_clken                          (<connected-to-fir_yn_clken>),                          //                          .clken
		.fir_yn_chipselect                     (<connected-to-fir_yn_chipselect>),                     //                          .chipselect
		.fir_yn_write                          (<connected-to-fir_yn_write>),                          //                          .write
		.fir_yn_readdata                       (<connected-to-fir_yn_readdata>),                       //                          .readdata
		.fir_yn_writedata                      (<connected-to-fir_yn_writedata>),                      //                          .writedata
		.fir_yn_byteenable                     (<connected-to-fir_yn_byteenable>),                     //                          .byteenable
		.hps_0_f2h_cold_reset_req_reset_n      (<connected-to-hps_0_f2h_cold_reset_req_reset_n>),      //  hps_0_f2h_cold_reset_req.reset_n
		.hps_0_f2h_debug_reset_req_reset_n     (<connected-to-hps_0_f2h_debug_reset_req_reset_n>),     // hps_0_f2h_debug_reset_req.reset_n
		.hps_0_f2h_stm_hw_events_stm_hwevents  (<connected-to-hps_0_f2h_stm_hw_events_stm_hwevents>),  //   hps_0_f2h_stm_hw_events.stm_hwevents
		.hps_0_f2h_warm_reset_req_reset_n      (<connected-to-hps_0_f2h_warm_reset_req_reset_n>),      //  hps_0_f2h_warm_reset_req.reset_n
		.hps_0_h2f_reset_reset_n               (<connected-to-hps_0_h2f_reset_reset_n>),               //           hps_0_h2f_reset.reset_n
		.hps_0_hps_io_hps_io_emac1_inst_TX_CLK (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CLK>), //              hps_0_hps_io.hps_io_emac1_inst_TX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_TXD0   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD0>),   //                          .hps_io_emac1_inst_TXD0
		.hps_0_hps_io_hps_io_emac1_inst_TXD1   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD1>),   //                          .hps_io_emac1_inst_TXD1
		.hps_0_hps_io_hps_io_emac1_inst_TXD2   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD2>),   //                          .hps_io_emac1_inst_TXD2
		.hps_0_hps_io_hps_io_emac1_inst_TXD3   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD3>),   //                          .hps_io_emac1_inst_TXD3
		.hps_0_hps_io_hps_io_emac1_inst_RXD0   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD0>),   //                          .hps_io_emac1_inst_RXD0
		.hps_0_hps_io_hps_io_emac1_inst_MDIO   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDIO>),   //                          .hps_io_emac1_inst_MDIO
		.hps_0_hps_io_hps_io_emac1_inst_MDC    (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDC>),    //                          .hps_io_emac1_inst_MDC
		.hps_0_hps_io_hps_io_emac1_inst_RX_CTL (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CTL>), //                          .hps_io_emac1_inst_RX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_TX_CTL (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CTL>), //                          .hps_io_emac1_inst_TX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_RX_CLK (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CLK>), //                          .hps_io_emac1_inst_RX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_RXD1   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD1>),   //                          .hps_io_emac1_inst_RXD1
		.hps_0_hps_io_hps_io_emac1_inst_RXD2   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD2>),   //                          .hps_io_emac1_inst_RXD2
		.hps_0_hps_io_hps_io_emac1_inst_RXD3   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD3>),   //                          .hps_io_emac1_inst_RXD3
		.hps_0_hps_io_hps_io_qspi_inst_IO0     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO0>),     //                          .hps_io_qspi_inst_IO0
		.hps_0_hps_io_hps_io_qspi_inst_IO1     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO1>),     //                          .hps_io_qspi_inst_IO1
		.hps_0_hps_io_hps_io_qspi_inst_IO2     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO2>),     //                          .hps_io_qspi_inst_IO2
		.hps_0_hps_io_hps_io_qspi_inst_IO3     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO3>),     //                          .hps_io_qspi_inst_IO3
		.hps_0_hps_io_hps_io_qspi_inst_SS0     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_SS0>),     //                          .hps_io_qspi_inst_SS0
		.hps_0_hps_io_hps_io_qspi_inst_CLK     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_CLK>),     //                          .hps_io_qspi_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_CMD     (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CMD>),     //                          .hps_io_sdio_inst_CMD
		.hps_0_hps_io_hps_io_sdio_inst_D0      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D0>),      //                          .hps_io_sdio_inst_D0
		.hps_0_hps_io_hps_io_sdio_inst_D1      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D1>),      //                          .hps_io_sdio_inst_D1
		.hps_0_hps_io_hps_io_sdio_inst_CLK     (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CLK>),     //                          .hps_io_sdio_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_D2      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D2>),      //                          .hps_io_sdio_inst_D2
		.hps_0_hps_io_hps_io_sdio_inst_D3      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D3>),      //                          .hps_io_sdio_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D0      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D0>),      //                          .hps_io_usb1_inst_D0
		.hps_0_hps_io_hps_io_usb1_inst_D1      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D1>),      //                          .hps_io_usb1_inst_D1
		.hps_0_hps_io_hps_io_usb1_inst_D2      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D2>),      //                          .hps_io_usb1_inst_D2
		.hps_0_hps_io_hps_io_usb1_inst_D3      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D3>),      //                          .hps_io_usb1_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D4      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D4>),      //                          .hps_io_usb1_inst_D4
		.hps_0_hps_io_hps_io_usb1_inst_D5      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D5>),      //                          .hps_io_usb1_inst_D5
		.hps_0_hps_io_hps_io_usb1_inst_D6      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D6>),      //                          .hps_io_usb1_inst_D6
		.hps_0_hps_io_hps_io_usb1_inst_D7      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D7>),      //                          .hps_io_usb1_inst_D7
		.hps_0_hps_io_hps_io_usb1_inst_CLK     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_CLK>),     //                          .hps_io_usb1_inst_CLK
		.hps_0_hps_io_hps_io_usb1_inst_STP     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_STP>),     //                          .hps_io_usb1_inst_STP
		.hps_0_hps_io_hps_io_usb1_inst_DIR     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_DIR>),     //                          .hps_io_usb1_inst_DIR
		.hps_0_hps_io_hps_io_usb1_inst_NXT     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_NXT>),     //                          .hps_io_usb1_inst_NXT
		.hps_0_hps_io_hps_io_spim1_inst_CLK    (<connected-to-hps_0_hps_io_hps_io_spim1_inst_CLK>),    //                          .hps_io_spim1_inst_CLK
		.hps_0_hps_io_hps_io_spim1_inst_MOSI   (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MOSI>),   //                          .hps_io_spim1_inst_MOSI
		.hps_0_hps_io_hps_io_spim1_inst_MISO   (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MISO>),   //                          .hps_io_spim1_inst_MISO
		.hps_0_hps_io_hps_io_spim1_inst_SS0    (<connected-to-hps_0_hps_io_hps_io_spim1_inst_SS0>),    //                          .hps_io_spim1_inst_SS0
		.hps_0_hps_io_hps_io_uart0_inst_RX     (<connected-to-hps_0_hps_io_hps_io_uart0_inst_RX>),     //                          .hps_io_uart0_inst_RX
		.hps_0_hps_io_hps_io_uart0_inst_TX     (<connected-to-hps_0_hps_io_hps_io_uart0_inst_TX>),     //                          .hps_io_uart0_inst_TX
		.hps_0_hps_io_hps_io_i2c0_inst_SDA     (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SDA>),     //                          .hps_io_i2c0_inst_SDA
		.hps_0_hps_io_hps_io_i2c0_inst_SCL     (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SCL>),     //                          .hps_io_i2c0_inst_SCL
		.hps_0_hps_io_hps_io_i2c1_inst_SDA     (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SDA>),     //                          .hps_io_i2c1_inst_SDA
		.hps_0_hps_io_hps_io_i2c1_inst_SCL     (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SCL>),     //                          .hps_io_i2c1_inst_SCL
		.hps_0_hps_io_hps_io_gpio_inst_GPIO09  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO09>),  //                          .hps_io_gpio_inst_GPIO09
		.hps_0_hps_io_hps_io_gpio_inst_GPIO35  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO35>),  //                          .hps_io_gpio_inst_GPIO35
		.hps_0_hps_io_hps_io_gpio_inst_GPIO40  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO40>),  //                          .hps_io_gpio_inst_GPIO40
		.hps_0_hps_io_hps_io_gpio_inst_GPIO48  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO48>),  //                          .hps_io_gpio_inst_GPIO48
		.hps_0_hps_io_hps_io_gpio_inst_GPIO53  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO53>),  //                          .hps_io_gpio_inst_GPIO53
		.hps_0_hps_io_hps_io_gpio_inst_GPIO54  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO54>),  //                          .hps_io_gpio_inst_GPIO54
		.hps_0_hps_io_hps_io_gpio_inst_GPIO61  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO61>),  //                          .hps_io_gpio_inst_GPIO61
		.memory_mem_a                          (<connected-to-memory_mem_a>),                          //                    memory.mem_a
		.memory_mem_ba                         (<connected-to-memory_mem_ba>),                         //                          .mem_ba
		.memory_mem_ck                         (<connected-to-memory_mem_ck>),                         //                          .mem_ck
		.memory_mem_ck_n                       (<connected-to-memory_mem_ck_n>),                       //                          .mem_ck_n
		.memory_mem_cke                        (<connected-to-memory_mem_cke>),                        //                          .mem_cke
		.memory_mem_cs_n                       (<connected-to-memory_mem_cs_n>),                       //                          .mem_cs_n
		.memory_mem_ras_n                      (<connected-to-memory_mem_ras_n>),                      //                          .mem_ras_n
		.memory_mem_cas_n                      (<connected-to-memory_mem_cas_n>),                      //                          .mem_cas_n
		.memory_mem_we_n                       (<connected-to-memory_mem_we_n>),                       //                          .mem_we_n
		.memory_mem_reset_n                    (<connected-to-memory_mem_reset_n>),                    //                          .mem_reset_n
		.memory_mem_dq                         (<connected-to-memory_mem_dq>),                         //                          .mem_dq
		.memory_mem_dqs                        (<connected-to-memory_mem_dqs>),                        //                          .mem_dqs
		.memory_mem_dqs_n                      (<connected-to-memory_mem_dqs_n>),                      //                          .mem_dqs_n
		.memory_mem_odt                        (<connected-to-memory_mem_odt>),                        //                          .mem_odt
		.memory_mem_dm                         (<connected-to-memory_mem_dm>),                         //                          .mem_dm
		.memory_oct_rzqin                      (<connected-to-memory_oct_rzqin>),                      //                          .oct_rzqin
		.reset_reset_n                         (<connected-to-reset_reset_n>),                         //                     reset.reset_n
		.fir_hn_address                        (<connected-to-fir_hn_address>),                        //                    fir_hn.address
		.fir_hn_clken                          (<connected-to-fir_hn_clken>),                          //                          .clken
		.fir_hn_chipselect                     (<connected-to-fir_hn_chipselect>),                     //                          .chipselect
		.fir_hn_write                          (<connected-to-fir_hn_write>),                          //                          .write
		.fir_hn_readdata                       (<connected-to-fir_hn_readdata>),                       //                          .readdata
		.fir_hn_writedata                      (<connected-to-fir_hn_writedata>),                      //                          .writedata
		.fir_hn_byteenable                     (<connected-to-fir_hn_byteenable>)                      //                          .byteenable
	);

